services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    HoPeter1018\ServiceHelperBundle\Command\:
        resource: '../../Command/*'
        tags: ['console.command']

    HoPeter1018\ServiceHelperBundle\Service\:
        resource: '../../Service/*'

    # TODO Root level registry
